### ISSUE TITLE
a question 

### ISSUE THREAD

**Issue by smopthy** [TheEricBurnett/Excellent-JSON#1]
if i have 10000more rows in  DATA ,
change the number in vba  still can'r work , 
have u alternative way to solution ?

**Comment by TheEricBurnett** [comment]
I don't know why I didn't see this issue earlier. I'm sorry!

Unfortunately I do not have another solution. My guess is that to handle something like that, you'd be best finding an Excel extension that can handle bulk data or perhaps export the data as a CSV file and then use another tool to convert it to JSON. Also, I think Excel might have a built in tool for exporting JSON, but I'm not sure it's immediately clear how it's best used.
